# Generated by Django 5.2.4 on 2025-07-27 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='irrigation.project')),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, null=True)),
                ('soil_type', models.CharField(max_length=100)),
                ('grass_type', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('water_pressure', models.FloatField(help_text='PSI')),
                ('flow_rate', models.FloatField(help_text='GPM')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yard', to='irrigation.project')),
            ],
        ),
        migrations.CreateModel(
            name='SketchElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('obstacle', 'Obstacle'), ('slope', 'Slope'), ('shade', 'Shade'), ('zone', 'Zone'), ('label', 'Label')], max_length=50)),
                ('geometry', models.JSONField(help_text='Geometry: point, polyline, or polygon as JSON')),
                ('properties', models.JSONField(default=dict, help_text='Extra properties like color, label, rotation')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketch_elements', to='irrigation.yard')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.IntegerField(blank=True, null=True)),
                ('total_flow', models.FloatField(blank=True, null=True)),
                ('area_covered', models.FloatField(blank=True, null=True)),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='irrigation.yard')),
            ],
        ),
        migrations.CreateModel(
            name='SprinklerHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_number', models.IntegerField(blank=True, help_text='Sequential number within the zone', null=True)),
                ('type', models.CharField(max_length=100)),
                ('location', models.JSONField(help_text='Coordinates like {x: 10, y: 5}')),
                ('throw_radius', models.FloatField()),
                ('flow_rate', models.FloatField()),
                ('angle', models.FloatField(default=360.0)),
                ('direction', models.FloatField(default=0.0, help_text='Angle in degrees where spray is directed (0 = right)')),
                ('overlap', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprinkler_heads', to='irrigation.zone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('yard', 'zone_number'), name='unique_zone_number_per_yard'),
        ),
        migrations.AddConstraint(
            model_name='sprinklerhead',
            constraint=models.UniqueConstraint(fields=('zone', 'head_number'), name='unique_head_number_per_zone'),
        ),
    ]
