# Generated by Django 5.2.4 on 2025-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinklerhead',
            name='location',
            field=models.JSONField(blank=True, help_text='Coordinates like {x: 10, y: 5}', null=True),
        ),
    ]
