# Generated by Django 5.2.4 on 2025-07-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_alter_sprinklerhead_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchelement',
            name='type',
            field=models.CharField(choices=[('obstacle', 'Obstacle'), ('slope', 'Slope'), ('full_sun', 'Full Sun'), ('partial_shade', 'Partial Shade'), ('full_shade', 'Full Shade'), ('label', 'Label')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sprinklerhead',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprinkler_heads', to='irrigation.zone'),
        ),
    ]
